name: publish

on:
    push:
        branches: [ develop ]
jobs:
    publish-hello-docker-image:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Checkout the repository
              uses: actions/checkout@v2

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                registry: ghcr.io
                username: ${{ github.actor }}
                password: ${{ secrets.GITHUB_TOKEN }}
            
            - name: Build the hello-docker Docker image
              run: |
                    docker build . --tag ghcr.io/balnarendrasapa/chatbot:sha-${{ env.GITHUB_SHA_SHORT }}
                    docker push ghcr.io/balnarendrasapa/chatbot:sha-${{ env.GITHUB_SHA_SHORT }}